sudo: required
services:
  - docker

before_install:
  - docker build -t vz/react-test -f ./client/Dockerfile.dev ./client
  # here one can build more other test projects
script:
  - docker run vz/react-test npm test -- --coverage

after_success:
  - docker build -t vimazac/multi-client ./client
  - docker build -t vimazac/multi-nginx ./nginx
  - docker build -t vimazac/multi-server ./server
  - docker build -t vimazac/multi-worker ./worker
# log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
  - docker push vimazac/multi-client
  - docker push vimazac/multi-nginx
  - docker push vimazac/multi-server
  - docker push vimazac/multi-worker